### ISSUE TITLE
Thaumcraft quest bug

### ISSUE THREAD

**Issue by TheLogan** [MyM-ModpackTeam/hypovolemia#102]
In the quest named Thaumcraft, in the Thaumcraft questline you are asked to create a iron capped wooden wand.
There are two different versions in NEI, one from Thaumcraft and one from Technomancy.
Thaumcraft can be created at a standard crafting table and at a arcane worktable, while Technomancy can only be made at an arcane worktable.
Incidentally the Arcane Worktable recipe is identical for both, and it's identical to the Crafting table version.

I've tried both recipes however and the real result is that both recipes give a wand from Thaumcraft. 

Here's the kicker though. The book recognizes neither, so as it stands the quest is not completable.
I assume it just needs to be more fuzzy.

**Comment by TheLogan** [comment]
I just spawned the technomancy wand (yay cheating!), and the quest is now completed. =)

**Comment by tyler489** [comment]
Duplicate #70 
Duplicate #71

**Comment by TheLogan** [comment]
Apologies =)

**Comment by Slind14** [comment]
Are you on the latest version? This should have been fixed since Alpha0.14

**Comment by TheLogan** [comment]
I just updated manually, just to be sure and went back and re-did the quest (hqm edit), but it's still broken, the thaumcraft wand is not accepted, only the technomancy wand is.

**Comment by drz2k** [comment]
I only see 2 iron capped wands from TC, none from technomancy.

Well created a wand in a table myself and added it as quest requirement. Please check it out with the commit below
