### ISSUE TITLE
Ordo shards make the wrong thing

### ISSUE THREAD

**Issue by tyler489** [MyM-ModpackTeam/hypovolemia#72]
ordo shards requre 3 accio essence with 2 iron when u put it in the alcmeisty set it makes Crucio essence and only consumes 1 essence

**Comment by ChetwyndKid** [comment]
Sorry to hear about that, THat should of been check by @caithleen who should of checked things when he decided to redo the thaumcraft section.

**Comment by tyler489** [comment]
stil broken with hotfix

**Comment by tyler489** [comment]
resolved

**Comment by TheLogan** [comment]
Having just tested this, it seems that it's still not fixed, the current recipe is 
1 accio
2 bones 
2 iron ingocts

The result is still that the accio is just converted into crucio

**Comment by tyler489** [comment]
in.14 it was vhanged to a acacio seed bag on .15 it was entirly changed
