### ISSUE TITLE
Duplicating Printed Engineering Circuit

### ISSUE THREAD

**Issue by TheLogan** [MyM-ModpackTeam/hypovolemia#95]
I've tried this with the other AE circuits and for me it only works with the PEC (Printed Engineering Circuit), however it happens so seldom it would seem that it's no saying if it could work with the others too.

What happened for me was
I placed my PEC onto the altar diviner, it never left my hand though but a copy was submitted to the blood altar, I picked the copy up from the blood altar and then I had 2. so I split the stack and placed one unit back onto the altar diviner, it copied itself again I picked up the copy from the blood altar, now I had three.
(I clicked r to sort my inventory a few times just to see that it wasn't just a visual glitch, that was however not the fact, they were actual copies).
This is where it becomes annoying. After having deleted the copies I tried it again after having started this article, and I haven't been able to repeat it, so whatever the conditions are, they are more than just "whenever", which means it'll be complicated to actually track it down, damnit.

**Comment by TheLogan** [comment]
I just noticed something really weird. While I'd gained 2 PEC's I'd magically lost 2 Fluix crystals.
I'd created 4 in all for the ME controller, but 2 had vanished at around the same time as I duplicated the PEC's

**Comment by TheLogan** [comment]
The rabbit hole deepens...
I had 3x64 coal and 1x64 charcoal.
I place the charcoal on the altar diviner, something jumps around in my inventory, and I now have 2x64 coal and 1x64 charcoal in my inventory, and 1x64 charcoal on the blood altar.
Meaning that instead of placing down 1x64 charcoal, it somehow converted 1x64 coal into charcoal and then placed that into the blood altar.. o_0
I picked up the charcoal from the blood altar, and again it was not just a visual glitch, this is for all intents and purposes charcoal.

**Comment by shadowpanther** [comment]
Just a guess: this may be happening because of the inventory mod that refills your hand with next item (or stack) when your hand becomes empty. While playing on the server, that only gave me visual glitches, but in single player that could potentially mess with the "master" copy of your inventory.

**Comment by TheLogan** [comment]
That actually makes perfect sense, I was wondering if it was happening because of the moving around stuff. Which you now say is a mod, yeah, that's not unlikely.
It just happened again, this time with a block of glass, and I think you're absolutely right about the whole singleplayer/multiplayer thingy, two different mods trying to mess with your inventory with no third-party (authoritative server) to check up on it, bad things happen.

**Comment by chuggafan** [comment]
This is probably because SOMEONE added two inventory management mods *glares at caith* if one was removed (which last i checked never happened...) then it should be fixed?

**Comment by TheLogan** [comment]
Well, disabling "auto-refill" fixes half the problems, things no longer duplicate.
However, I've noticed that at times things revert in state.

Say I have 3x64 coal and 1x64 charcoal
I add 1x64 charcoal to the altar
So now I have 2x64 coal and 1x64 charcoal in my inventory and 1x64 charcoal on the altar.

Every time it has happened it seems to be something that the altar has created reverts to the base 
Coal => charcoal
Logic Processor => Printed Logic Circuit

etc

**Comment by TheLogan** [comment]
Damnit. The duplication is still an issue. Just had it happen with certus quartz crystals.
Though rather oddly 4 became 7, rather than 8 (all previous times it has always been an exact duplication)

**Comment by TheLogan** [comment]
However, I just lost 3 Logic processors, so my previous observations are wrong, things can indeed transmorph

**Comment by drz2k** [comment]
Mousetweaks or inventory tweaks .... which to keep? :D

**Comment by chuggafan** [comment]
invtweaks, i perfer it on a multiplicitive scale ;)

**Comment by Slind14** [comment]
does the issue exist with the latest versions, too?

**Comment by chuggafan** [comment]
I don't know why it wouldn't it's a mod conflict between two mods trying to do the same job, which dupes the items

**Comment by Slind14** [comment]
well if it isn't fixed, we can report it and it would be likely that one of them is going to put in some work to make them work nice together.

**Comment by drz2k** [comment]
https://github.com/MyM-ModpackTeam/hypovolemia/commit/b168d5ee99418b80fcbe60e4000a8f8b1b87d985

**Comment by shaggy1395** [comment]
I've only had experience with Inventory Tweaks, zero duplication issues across multiple versions, both MP and SP in multiple packs.  I'd vote for that one if they can't be made to cooperate.

**Comment by SirWilli** [comment]
Is this issue only in MP or in SP too? I couldn't reproduce it in both.
(Placing a PEC into Blood Altar or Altar Diviner doesn't dupe for me.)

**Comment by chuggafan** [comment]
only happens when using mousetweaks and inventory tweaks and middle clicking, causes both to sort at the same time duplicating it on the client

**Comment by SirWilli** [comment]
So the dupe has nothing to do with Blood Altar or Altar Diviner?

**Comment by SirWilli** [comment]
@chuggafan just tested, if I disable InvTweaks and press the on the mouse wheel nothing happens. So I have no idea what you are talking about

**Comment by chuggafan** [comment]
He clicked r, you need both mousetweaks and inventory tweaks enabled for this to work

**Comment by SirWilli** [comment]
I tried that, just sorts the inventory but doesn't dupe.

**Comment by chuggafan** [comment]
no clue if self solved then, may be, @TheLogan can you confirm by testing again if it's gone or not?

**Comment by drz2k** [comment]
Pending to closure T-3
